name: fl_advanced_tab_manager
description: Advanced docking manager Auto-hide strips with background, save/load perspective, drag from flyout.
publish_to: "none"
publisher: Givi Bibileishvili
version: 0.4.4+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
