name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Flutter SDK
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'     # or specify: '3.24.0'
          channel: 'stable'

      # Get dependencies
      - name: Install dependencies
        run: flutter pub get

      # Format check (optional)
      # - name: Check formatting
      #   run: flutter format --set-exit-if-changed .

      # Analyze code
      - name: Analyze project source
        run: flutter analyze

      # Run tests
      - name: Run tests
        run: flutter test
